// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _required(_webApiKey, 'FIREBASE_WEB_API_KEY'),
    appId: _required(_webAppId, 'FIREBASE_WEB_APP_ID'),
    messagingSenderId: _required(
      _messagingSenderId,
      'FIREBASE_MESSAGING_SENDER_ID',
    ),
    projectId: _required(_projectId, 'FIREBASE_PROJECT_ID'),
    authDomain: _required(_authDomain, 'FIREBASE_AUTH_DOMAIN'),
    storageBucket: _required(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
    measurementId: _required(_webMeasurementId, 'FIREBASE_WEB_MEASUREMENT_ID'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _required(_androidApiKey, 'FIREBASE_ANDROID_API_KEY'),
    appId: _required(_androidAppId, 'FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: _required(
      _messagingSenderId,
      'FIREBASE_MESSAGING_SENDER_ID',
    ),
    projectId: _required(_projectId, 'FIREBASE_PROJECT_ID'),
    storageBucket: _required(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _required(_iosApiKey, 'FIREBASE_IOS_API_KEY'),
    appId: _required(_iosAppId, 'FIREBASE_IOS_APP_ID'),
    messagingSenderId: _required(
      _messagingSenderId,
      'FIREBASE_MESSAGING_SENDER_ID',
    ),
    projectId: _required(_projectId, 'FIREBASE_PROJECT_ID'),
    storageBucket: _required(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
    iosBundleId: _required(_iosBundleId, 'FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _required(_iosApiKey, 'FIREBASE_IOS_API_KEY'),
    appId: _required(_iosAppId, 'FIREBASE_IOS_APP_ID'),
    messagingSenderId: _required(
      _messagingSenderId,
      'FIREBASE_MESSAGING_SENDER_ID',
    ),
    projectId: _required(_projectId, 'FIREBASE_PROJECT_ID'),
    storageBucket: _required(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
    iosBundleId: _required(_iosBundleId, 'FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _required(_webApiKey, 'FIREBASE_WEB_API_KEY'),
    appId: _required(_windowsAppId, 'FIREBASE_WINDOWS_APP_ID'),
    messagingSenderId: _required(
      _messagingSenderId,
      'FIREBASE_MESSAGING_SENDER_ID',
    ),
    projectId: _required(_projectId, 'FIREBASE_PROJECT_ID'),
    authDomain: _required(_authDomain, 'FIREBASE_AUTH_DOMAIN'),
    storageBucket: _required(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
    measurementId: _required(
      _windowsMeasurementId,
      'FIREBASE_WINDOWS_MEASUREMENT_ID',
    ),
  );

  static const _projectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
  static const _messagingSenderId = String.fromEnvironment(
    'FIREBASE_MESSAGING_SENDER_ID',
  );
  static const _storageBucket = String.fromEnvironment(
    'FIREBASE_STORAGE_BUCKET',
  );
  static const _authDomain = String.fromEnvironment('FIREBASE_AUTH_DOMAIN');

  static const _webApiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY');
  static const _webAppId = String.fromEnvironment('FIREBASE_WEB_APP_ID');
  static const _webMeasurementId = String.fromEnvironment(
    'FIREBASE_WEB_MEASUREMENT_ID',
  );

  static const _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
  );
  static const _androidAppId = String.fromEnvironment(
    'FIREBASE_ANDROID_APP_ID',
  );

  static const _iosApiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY');
  static const _iosAppId = String.fromEnvironment('FIREBASE_IOS_APP_ID');
  static const _iosBundleId = String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID');

  static const _windowsAppId = String.fromEnvironment(
    'FIREBASE_WINDOWS_APP_ID',
  );
  static const _windowsMeasurementId = String.fromEnvironment(
    'FIREBASE_WINDOWS_MEASUREMENT_ID',
  );

  static String _required(String value, String name) {
    if (value.isEmpty) {
      throw StateError(
        'Missing Firebase config value: $name. '
        'Pass it with --dart-define or '
        '--dart-define-from-file=config/firebase.local.json.',
      );
    }

    return value;
  }
}
